# version: '3.8'

services:
  #1. Database Service
  db:
    image: postgres:15-alpine
    container_name: smart_learning_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-smart_learning_db}"
      interval: 5s
      timeout: 5s
      retries: 5

  #2. Backend Service (FastAPI)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart_learning_backend
    restart: always
    ports:
     - "${BACKEND_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      #- JWT_SECRET=your_super_secret_jwt_key
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  #3. Frontend Service (React + Vite)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart_learning_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: