"""Add attachments and refine stream models

Revision ID: 993f79586a38
Revises: d5b3d6c296e6
Create Date: 2026-08-05 03:25:27.297593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993f79586a38'
down_revision: Union[str, None] = 'd5b3d6c296e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('attachments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attachments', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attachments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('attachments', 'created_at')
    op.drop_column('attachments', 'file_size')
    # ### end Alembic commands ###
