"""add identity to learning tables

Revision ID: b7d1e8f4a2c3
Revises: a29966dfbf07
Create Date: 2026-08-05 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b7d1e8f4a2c3"
down_revision: Union[str, Sequence[str], None] = "a29966dfbf07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLES_WITH_BIGINT_IDS = (
    "classes",
    "class_enrollments",
    "posts",
    "attachments",
    "comments",
    "assignments",
    "submissions",
)


def _is_identity(table_name: str) -> bool:
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            """
            SELECT is_identity
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = :table_name
              AND column_name = 'id'
            """
        ),
        {"table_name": table_name},
    ).scalar()
    return result == "YES"


def _has_id_default(table_name: str) -> bool:
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            """
            SELECT column_default
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = :table_name
              AND column_name = 'id'
            """
        ),
        {"table_name": table_name},
    ).scalar()
    return result is not None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    for table_name in TABLES_WITH_BIGINT_IDS:
        # Postgres implicitly creates these BigInteger PK columns as BIGSERIAL
        # (a sequence-backed DEFAULT), which already auto-increments. Adding
        # GENERATED AS IDENTITY is only valid on a column with no default at all.
        if not _is_identity(table_name) and not _has_id_default(table_name):
            op.execute(
                sa.text(
                    f'ALTER TABLE "{table_name}" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY'
                )
            )
        op.execute(
            sa.text(
                f"""
                SELECT setval(
                    pg_get_serial_sequence('{table_name}', 'id'),
                    COALESCE((SELECT MAX(id) FROM "{table_name}"), 0) + 1,
                    false
                )
                """
            )
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    for table_name in reversed(TABLES_WITH_BIGINT_IDS):
        if _is_identity(table_name):
            op.execute(
                sa.text(
                    f'ALTER TABLE "{table_name}" ALTER COLUMN id DROP IDENTITY IF EXISTS'
                )
            )
