"""Add stream and comments tables

Revision ID: d5b3d6c296e6
Revises: 91a93e9b8141
Create Date: 2026-08-04 15:59:19.925843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b3d6c296e6'
down_revision: Union[str, None] = '91a93e9b8141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attachments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('posts', sa.Column('post_type', sa.String(), nullable=True))
    op.alter_column('posts', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posts', 'post_type')
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attachments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assignments', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
