from app.schemas.admin import (
    UserAdminResponse,
    UserStatusUpdateRequest,
)
from app.schemas.assignments import (
    AssignmentCreateRequest,
    AssignmentResponse,
    SubmissionCreateRequest,
    SubmissionResponse,
    GradeSubmissionRequest,
    AssignmentStatsResponse,
    AssignmentListResponse,
)
from app.schemas.auth import (
    AuthResponse,
    ChangePasswordRequest,
    ForgotPasswordRequest,
    LoginRequest,
    MessageResponse,
    RefreshTokenRequest,
    RegisterRequest,
    ResetPasswordRequest,
    TokenPayload,
    TokenResponse,
    UserResponse,
    VerifyOTPRequest,
    VerifyOTPResponse,
)
from app.schemas.classes import (
    ClassCreateRequest,
    ClassJoinRequest,
    ClassResponse,
    UserSummaryResponse,
)
from app.schemas.dashboard import (
    AdminDashboardResponse,
    StudentDashboardResponse,
    TeacherClassSummary,
    TeacherDashboardResponse,
    UpcomingAssignmentSummary,
)
from app.schemas.posts import (
    CommentCreateRequest,
    CommentResponse,
    PostCreateRequest,
    PostResponse,
)

__all__ = [
    "RegisterRequest",
    "LoginRequest",
    "RefreshTokenRequest",
    "ChangePasswordRequest",
    "ForgotPasswordRequest",
    "VerifyOTPRequest",
    "VerifyOTPResponse",
    "ResetPasswordRequest",
    "UserResponse",
    "TokenResponse",
    "AuthResponse",
    "TokenPayload",
    "MessageResponse",
    "ClassCreateRequest",
    "ClassJoinRequest",
    "UserSummaryResponse",
    "ClassResponse",
    "AdminDashboardResponse",
    "TeacherClassSummary",
    "UpcomingAssignmentSummary",
    "TeacherDashboardResponse",
    "StudentDashboardResponse",
    "PostCreateRequest",
    "PostResponse",
    "CommentCreateRequest",
    "CommentResponse",
    "UserAdminResponse",
    "UserStatusUpdateRequest",
    "AssignmentCreateRequest",
    "AssignmentResponse",
    "SubmissionCreateRequest",
    "SubmissionResponse",
    "GradeSubmissionRequest",
    "AssignmentStatsResponse",
    "AssignmentListResponse",
]